app:
  env: dev
  name: go-megatron
  graceful_timeout: "10s"
log:
  option: stdout
  level: info
http:
  port: "8080"
  read_timeout: "30s"
  write_timeout: "30s"
  shutdown_timeout: "10s"
database:
  host: db-vm-pg.payments-dev.amartha.id
  port: 5432
  user: payment_dev
  password: SXlj16b9FeuH
  dbname: acuan_transaction
  dbschema: public
  max_conns: 10
  min_conns: 2
kafka:
  publishers:
    journal_stream:
      brokers:
        - kafka01-bootstrap.dev.amartha.id:9094
      topic: journal_stream
    transformer_stream_dlq:
      brokers:
        - kafka01-bootstrap.dev.amartha.id:9094
      topic: transformer_stream_dlq
  consumers:
    health_check_port: 80
    papa_transaction_stream:
      brokers:
        - kafka01-bootstrap.dev.amartha.id:9094
      consumer_group: go-megatron-papa_transaction_stream
      topic: transaction_stream
    lsm_loan_logs:
      brokers:
        - kafka01-bootstrap.dev.amartha.id:9094
      consumer_group: go-megatron-loan_logs
      topic: loan_logs
    bre_billing_repayment_logs:
      brokers:
        - kafka01-bootstrap.dev.amartha.id:9094
      consumer_group: go-megatron-billing_repayment_logs
      topic: billing_repayment_logs
    acuan_transaction_notif:
      brokers:
        - kafka01-bootstrap.dev.amartha.id:9094
      consumer_group: go-megatron-acuan-transaction-notif
      topic: acuan-transaction-notif.local
    transformer_stream_dlq:
      brokers:
        - kafka01-bootstrap.dev.amartha.id:9094
      consumer_group: go-megatron-transformer_stream_dlq
      topic: transformer_stream_dlq

go_accounting:
  base_url: https://go-accounting-dev.amartha.id
  secret_key: amartha-jy4uLtdYWx
  retry_count: 3
  retry_wait_time: 100
  timeout: 1s

ddd_notification:
  base_url: https://api-gw-dev.amartha.id/notification-api
  retry_count: 3
  retry_wait_time: 100
  slack_channel: pas-notifications-dev
  title_bot: Payment Accounting System Alert Bot

feature_flag_sdk:
  url: https://feature-dev.amartha.id/api
  token: "*:development.5e969ec15b9210c907483b31266de5b7709a2bed1a62811e5784ea4e"
  env: development
  refresh_interval: 5m

config_account:
  map_account_order_types_entity_product:
    "001_adm":
      - "default": "114001000000011"
      - "broilerx": "121001000000003"
      - "chickin": "121001000000005"
      - "group loan": "121001000000012"
      - "modal": "121001000000009"
      - "efishery": "121001000000014"
      - "indosat": "121001000000019"
      - "broilerx_loan": "121001000000003"
      - "chickin_loan": "121001000000005"
      - "normal": "121001000000012"
      - "modal_loan": "121001000000009"
      - "efishery_loan": "121001000000014"
      - "indosat_loan": "121001000000019"
      - "modal_paylater_loan": "121001000000003"
    "003_adm":
      - "default": "114003000000016"
    "005_adm":
      - "default": "114005000000030"
      - "broilerx": "121005000000021"
      - "chickin": "121005000000022"
      - "group loan": "121005000000023"
      - "modal": "121005000000024"
      - "efishery": "121005000000025"
      - "indosat": "121005000000026"
      - "broilerx_loan": "121005000000021"
      - "chickin_loan": "121005000000022"
      - "normal": "121005000000023"
      - "modal_loan": "121005000000024"
      - "efishery_loan": "121005000000025"
      - "indosat_loan": "121005000000026"
      - "modal_paylater_loan": "121005000000021"
    "001_mff":
      - "default": "121001000000010"
    "005_mff":
      - "default": "121005000000031"
    "001_mfm":
      - "default": "261001000000013"
    "005_mfm":
      - "default": "261005000000016"
    "001_mfw":
      - "default": "114001000000011"
      - "default2": "114001000000005"
    "005_mfw":
      - "default": "114005000000030"
      - "default2": "114005000000030"
    "001_rfd":
      - "default": "121001000000009"
    "005_rfd":
      - "default": "121005000000024"

    "001_dsb":
      - "default": ""
      - "broilerx": "121001000000003"
      - "chickin": "121001000000005"
      - "group loan": "121001000000012"
      - "modal": "121001000000009"
      - "efishery": "121001000000014"
      - "indosat": "121001000000019"
      - "agriaku": "121001000000035"
      - "broilerx_loan": "121001000000003"
      - "chickin_loan": "121001000000005"
      - "normal": "121001000000012"
      - "modal_loan": "121001000000009"
      - "efishery_loan": "121001000000014"
      - "indosat_loan": "121001000000019"
      - "modal_paylater_loan": "121001000000003"
      - "agriaku_loan": "121001000000035"
    "005_dsb":
      - "default": ""
      - "broilerx": "121005000000021"
      - "chickin": "121005000000022"
      - "group loan": "121005000000023"
      - "modal": "121005000000024"
      - "efishery": "121005000000025"
      - "indosat": "121005000000026"
      - "agriaku": ""
      - "broilerx_loan": "121005000000021"
      - "chickin_loan": "121005000000022"
      - "normal": "121005000000023"
      - "modal_loan": "121005000000024"
      - "efishery_loan": "121005000000025"
      - "indosat_loan": "121005000000026"
      - "modal_paylater_loan": "121005000000021"
      - "agriaku_loan": ""

    "001_rpy":
      - "default": ""
      - "broilerx_loan": "121001000000006"
      - "chickin_loan": "121001000000007"
      - "graduation_loan": "121001000000013"
      - "normal": "121001000000008"
      - "modal_loan": "121001000000010"
      - "efishery_loan": "121001000000015"
      - "indosat_loan": "121001000000020"
      - "modal_paylater_loan": "121001000000017"
      - "agriaku_loan": "121001000000036"
    "005_rpy":
      - "default": ""
      - "broilerx_loan": "121005000000028"
      - "chickin_loan": "121005000000027"
      - "graduation_loan": "121005000000029"
      - "normal": "121005000000030"
      - "modal_loan": "121005000000031"
      - "efishery_loan": "121005000000032"
      - "indosat_loan": "121005000000033"
      - "modal_paylater_loan": "121005000000034"
      - "agriaku_loan": ""
    "001_tup":
      - "default": "114001000000003"
    "005_tup":
      - "default": "114005000000030"

  map_account_entity_trx_types:
    "001_rfdmp":
      - "debit": "121001000000009"
      - "credit": "261001000000013"
    "005_rfdmp":
      - "debit": "121005000000024"
      - "credit": "261005000000016"
    "001_1001_dsbpd":
      - "debit": "121001000000012"
      - "credit": "121001000000008"
    "005_1001_dsbpd":
      - "debit": "121005000000023"
      - "credit": "121005000000030"
    "001_1011_dsbpd":
      - "debit": "121001000000009"
      - "credit": "121001000000010"
    "005_1011_dsbpd":
      - "debit": "121005000000024"
      - "credit": "121005000000031"
    "001_admme":
      - "credit": "145001000000002"
    "003_admme":
      - "credit": "143003000000003"

  map_repayment_cit_entity:
    "001": "121001000000101"
    "005": "121005000000104"

  map_bank_ho_repayment_pooling_entity:
    "001": "114001000000004"
    "005": "114005000000006"

  map_dsbpi_account_entity:
    "001": "121001000000009"
    "005": "121005000000105"