replicaCount: 1

env: dev

image:
  repository: asia-southeast2-docker.pkg.dev/amartha-ewallet-dev-370304/docker/go-megatron
  pullPolicy: IfNotPresent
  tag: ""

args:
  - ./go-megatron-consumer
  - run
  - "-n=transaction_stream"

serviceAccount:
  create: true
  annotations: {}
  name: go-megatron-consumer-transactionstream

extraEnvs: []

readinessProbe:
  failureThreshold: 10
  httpGet:
    path: /health/consumer
    port: 80
    scheme: HTTP
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10

resources:
  limits:
    cpu: 200m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 200Mi

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "80"
  prometheus.io/path: "/metrics"

autoscaling:
  enabled: false
  
volumeMounts:
  - name: secret-volume
    mountPath: /opt/Amartha/config
    readOnly: true

volumes:
  - name: secret-volume
    secret:
      secretName: go-megatron-consumer-transactionstream-vault-service

vault:
  enabled: true
  auth:
    method: "kubernetes"
    kubernetes:
      role: go-megatron-consumer-transactionstream
      serviceAccount: go-megatron-consumer-transactionstream
  secrets:
    service:
      secretPath: apps/core-finance-platform/GO_MEGATRON