replicaCount: 30

env: prod

image:
  repository: asia-southeast2-docker.pkg.dev/amartha-ewallet-dev-370304/docker/go-megatron
  pullPolicy: IfNotPresent
  tag: ""

args:
  - ./go-megatron-consumer
  - run
  - "-n=acuan_transaction_notif"

serviceAccount:
  create: true
  annotations: {}
  name: go-megatron-consumer-acuantransactionnotif

extraEnvs: []

readinessProbe:
  failureThreshold: 10
  httpGet:
    path: /health/consumer
    port: 80
    scheme: HTTP
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10

resources:
  limits:
    cpu: 1800m
    memory: 200Mi
  requests:
    cpu: 1500m
    memory: 100Mi

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "80"
  prometheus.io/path: "/metrics"

# autoscaling:
#   enabled: true
#   minReplicas: 10
#   maxReplicas: 30
#   targetMemoryUtilizationPercentage: 80
#   targetCPUUtilizationPercentage: 80

volumeMounts:
  - name: secret-volume
    mountPath: /opt/Amartha/config
    readOnly: true

volumes:
  - name: secret-volume
    secret:
      secretName: go-megatron-consumer-acuantransactionnotif-vault-service

vault:
  enabled: true
  auth:
    method: "kubernetes"
    kubernetes:
      role: go-megatron-consumer-acuantransactionnotif
      serviceAccount: go-megatron-consumer-acuantransactionnotif
  secrets:
    service:
      secretPath: apps/core-finance-platform/GO_MEGATRON